library identifier: 'diamol-jenkins-library@master', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/sixeyed/diamol-jenkins-library.git'])

multiArchBuild linuxContext: 'images/openjdk/jdk', 
               linuxArmContext: 'images/openjdk/jdk/linux/arm', 
               windowsContext: 'images/openjdk/jdk/windows',
               repoName: 'diamol/openjdk',
               tag: 'jdk'