FROM diamol/dotnet-sdk:2e AS builder

WORKDIR /src
COPY src/Numbers.Web/Numbers.Web.csproj .
RUN dotnet restore

COPY src/Numbers.Web/ .
RUN dotnet publish -c Release -o /out Numbers.Web.csproj

# app image
FROM diamol/dotnet-aspnet:2e

ENV RngApi__Url=http://numbers-api:8080/rng

CMD curl --fail http://numbers-api:8080/rng && \
    dotnet Numbers.Web.dll

WORKDIR /app
COPY --from=builder /out/ .