pipeline {
    agent any
    environment {
       REGISTRY = "registry.local:5000"
       UAT_ENGINE = "ip172-18-0-69-bthrciiosm4g00b8b730-2376.direct.labs.play-with-docker.com:80"
       PROD_ENGINE = "ip172-18-0-69-bthrciiosm4g00b8b730-2376.direct.labs.play-with-docker.com:80"
    }
    stages {
        stage('Verify') {
            steps {
                dir('ch15/exercises') {
                    sh 'chmod +x ./ci/00-verify.bat'
                    sh './ci/00-verify.bat'
                }
            }
        }
        stage('Build') {
            steps {
                dir('ch15/exercises') {
                    sh 'chmod +x ./ci/01-build.bat'
                    sh './ci/01-build.bat'
                }
            }
        }
        stage('Test') {
            steps {
                dir('ch15/exercises') {
                    sh 'chmod +x ./ci/02-test.bat'
                    sh './ci/02-test.bat'
                }
            }
        }
        stage('Push') {
            steps {
                dir('ch15/exercises') {
                    sh 'chmod +x ./ci/03-push.bat'
                    sh './ci/03-push.bat'
                    echo "Pushed web to http://$REGISTRY/v2/diamol/ch15-timecheck/tags/list"
                }
            }
        }
        stage('UAT') {
            steps {
                withCredentials([file(credentialsId: 'docker-ca.pem', variable: 'ca'),
                                 file(credentialsId: 'docker-cert.pem', variable: 'cert'),
                                 file(credentialsId: 'docker-key.pem', variable: 'key')]) {                    
                    dir('ch15/exercises') {
                        sh 'chmod +x ./ci/04-uat.bat'
                        sh './ci/04-uat.bat'
                        echo "Deployed to UAT"
                    }
                }
            }
        }
        stage('Await approval') {
            steps {
                input message: 'Deploy to prod?', ok: 'Do it!'
            }
        }
        stage('Production') {
            steps {
                withCredentials([file(credentialsId: 'docker-ca.pem', variable: 'ca'),
                                 file(credentialsId: 'docker-cert.pem', variable: 'cert'),
                                 file(credentialsId: 'docker-key.pem', variable: 'key')]) {                    
                    dir('ch15/exercises') {
                        sh 'chmod +x ./ci/05-deploy.bat'
                        sh './ci/05-deploy.bat'
                        echo "Deployed to PROD"
                    }
                }
            }
        }
    }
}