services:
  nginx:
    image: diamol/nginx:2e
    ports:
      - "80:80"
    volumes:
      - "./sites-enabled:/etc/nginx/sites-enabled"
    networks:
      - ch20

networks:
  ch20:
    name: ch20
    external: true
