FROM diamol/golang:2e AS builder

COPY go.mod main.go /go/
RUN go build -o /hello

# app
FROM mcr.microsoft.com/windows/nanoserver:ltsc2022

CMD ["/app/hello"]

WORKDIR /app
COPY --from=builder /hello .