FROM --platform=$BUILDPLATFORM diamol/golang:2e AS builder
ARG TARGETOS
ARG TARGETARCH

ENV GOOS=${TARGETOS} \
    GOARCH=${TARGETARCH}

COPY go.mod main.go /go/
RUN go build -o /hello

# app
FROM diamol/base:2e

CMD ["/app/hello"]

WORKDIR /app
COPY --from=builder --chmod=777 /hello .
