library identifier: 'diamol-jenkins-library@master', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/sixeyed/diamol-jenkins-library.git'])

multiArchBuild linuxContext: 'ch03/exercises/web-ping-optimized', 
               windowsContext: 'ch03/exercises/web-ping-optimized'