services:


  elasticsearch:
    image: diamol/elasticsearch:2e
    ports:
      - "9200:9200"  
      
  fluentd:
    image: diamol/fluentd:2e
    environment:
      FLUENTD_CONF: elasticsearch.conf
    volumes:
      - ./conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch

  kibana:
    image: diamol/kibana:2e
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
