FROM diamol/golang:2e AS builder

COPY go.mod main.go /go/
RUN go build -o /server
RUN chmod +x /server

# app
FROM diamol/base:2e

EXPOSE 80
CMD ["/web/server"]
ENV USER="sixeyed"

WORKDIR /web
COPY --from=builder /server .
COPY index.html .