ARG DOTNET_VERSION
ARG WINDOWS_VERSION_CODE
FROM mcr.microsoft.com/dotnet/sdk:${DOTNET_VERSION}-nanoserver-${WINDOWS_VERSION_CODE}

# for Windows LTSC2025:
# FROM sixeyed/dotnet-sdk:8.0-windows-ltsc2025-amd64