FROM mcr.microsoft.com/dotnet/sdk:8.0.400-nanoserver-ltsc2022

LABEL framework="dotnet"
LABEL version="8.0"
LABEL description=".NET 8.0 SDK"
LABEL owner="golden-images@sixeyed.com"

WORKDIR src
COPY global.json .