library identifier: 'diamol-jenkins-library@master', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/sixeyed/diamol-jenkins-library.git'])

multiArchBuild linuxContext: 'ch08/exercises/numbers/numbers-api', 
               windowsContext: 'ch08/exercises/numbers/numbers-api'