<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="prometheus-net.AspNetCore" Version="3.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\core\ToDoList.Core.csproj" />
    <ProjectReference Include="..\entities\ToDoList.Entities.csproj" />
    <ProjectReference Include="..\messaging\ToDoList.Messaging.csproj" />
    <ProjectReference Include="..\model\ToDoList.Model.csproj" />
  </ItemGroup>
</Project>