FROM diamol/dotnet-sdk:2e AS sdk

# app build
FROM sdk AS builder
WORKDIR /src
COPY src/TimeCheck.csproj .
RUN dotnet restore
COPY src /src
RUN dotnet publish -c Release -o /out TimeCheck.csproj

#  utility build
FROM sdk as utility
WORKDIR /utility
COPY utility/Tail.csproj .
RUN dotnet restore
COPY utility /utility
RUN dotnet publish -c Release -o /out Tail.csproj

# app image
FROM diamol/dotnet-runtime:2e AS base

ENV Application__Version="3.0" \
    Output__Console="false" \
    DOTNET_USE_POLLING_FILE_WATCHER="true"

WORKDIR /logs
RUN echo Init > timecheck.log

WORKDIR /app
COPY --from=builder /out/ .
COPY --from=utility /out/ .

FROM base AS windows
CMD start /B dotnet TimeCheck.dll && dotnet Tail.dll /logs timecheck.log

FROM base AS linux
CMD dotnet TimeCheck.dll & dotnet Tail.dll /logs timecheck.log