services:
  numbers-api:
    image: ghcr.io/diamol2e/ch08-numbers-api:2e
    ports:
      - "8081:8080"
    networks:
      - app-net

  numbers-web:
    image: ghcr.io/diamol2e/ch08-numbers-web:2e
    environment:
      - RngApi__Url=http://numbers-api:8080/rng
    depends_on:
      - numbers-api
    ports:
      - "8080:8080"
    networks:
      - app-net

networks:
  app-net: {}