library identifier: 'diamol-jenkins-library@master', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/sixeyed/diamol-jenkins-library.git'])

multiArchBuild linuxContext: 'ch02/exercises/hello-diamol/linux', 
               windowsContext: 'ch02/exercises/hello-diamol/windows'