services:
  accesslog:
    image: diamol/ch18-access-log:2e
    ports:
      - "8030:80"
    environment:
      APP_RELEASE: "25.03"
    volumes:
      - ./config/access-log/test:/app/config-override
    networks:
      - iotd-net

  iotd:
    image: diamol/ch18-image-of-the-day:2e
    ports:
      - "8020:80"
    environment:
      CONFIG_SOURCE_PATH: "/app/config-override/application.properties"
      IOTD_RELEASE: "25.03"
    volumes:
      - ./config/image-of-the-day/test:/app/config-override
    networks:
      - iotd-net

  image-gallery:
    image: diamol/ch18-image-gallery:2e
    ports:
      - "8010:80"
    environment:
      IG_RELEASE: "25.03"
    volumes:
      - ./config/image-gallery/test:/app/config-override
    depends_on:
      - accesslog
      - iotd
    networks:
      - iotd-net

networks:
  iotd-net:
