services:
  accesslog:
    image: diamol/ch18-access-log:2e
    ports:
      - "8030:80"
    networks:
      - iotd-net

  iotd:
    image: diamol/ch18-image-of-the-day:2e
    ports:
      - "8020:80"
    networks:
      - iotd-net

  image-gallery:
    image: diamol/ch18-image-gallery:2e
    ports:
      - "8010:80"
    depends_on:
      - accesslog
      - iotd
    networks:
      - iotd-net

networks:
  iotd-net:
