pipeline {
    agent any 
    stages {
        stage('Verify') {
            steps {
                echo 'Verifying Docker...'
                sh 'docker version'
                echo 'Verifying Docker Compose...'
                sh 'docker-compose version'
            }
        }
    }
}