pipeline {
    agent any
    environment {
       REGISTRY = "registry.diamol:5000"
    }
    stages {
        stage('Verify') {
            dir('ch11/exercises') {
                steps {
                    sh 'ls -l'
                    sh './ci/00-verify.bat'
                }
            }
        }
        stage('Build') {
            dir('ch11/exercises') {
                steps {
                    sh './ci/01-build.bat'
                }
            }
        }
        stage('Test') {
            dir('ch11/exercises') {
                steps {
                    sh './ci/02-test.bat'
                }
            }
        }
        stage('Push') {
            dir('ch11/exercises') {
                steps {
                    sh './ci/03-push.bat'
                }
            }
        }
    }
}