name: images-windows-ltsc2019

on:
  push:
    branches:
      - "2e"
    paths:
      - ".github/workflows/images-windows-ltsc2019.yaml"
  workflow_dispatch:
    inputs:
      filter:
        required: false
        default: ''
        description: "Image filter"

jobs:
  images-windows-ltsc2019:
    runs-on: windows-2019
    steps:
      - name: Docker Hub login
        shell: pwsh
        run: |
          docker login -u $env:USER -p $env:TOKEN
        env:
          USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: actions/checkout@master
      - uses: ./.github/actions/build
        with:
          filter: "${{ github.event.inputs.filter }}"