name: Windows LTSC2022 image build

on:
  workflow_dispatch:

jobs:
  images-ltsc2022:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@master
      - name: Build and push Windows images
        working-directory: build
        run: |
          docker login -u $env:USER -p $env:TOKEN
          ./build.ps1 -Images
        env:
          USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
