name: Linux AMD64 image build

on:
  push:
    branches:
      - "2e"
    paths:
      - "images/**"
      - ".github/workflows/images-linux-amd64.yaml"

jobs:
  images-linux-amd64:
    runs-on: ubuntu-latest
    steps:
    
      - name: Registry login    
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: actions/checkout@master

      - name: Build and push Linux AMD64 images
        working-directory: build
        shell: pwsh
        run: |
          ./build.ps1 -Images
