name: Linux AMD64 image build

on:
  push:
    branches:
      - "2e"
    paths:
      - "images/**"
      - "build/**"
      - ".github/workflows/images-linux-amd64.yaml"

jobs:
  images-linux-amd64:
    runs-on: ubuntu-latest
    steps:
    
      - name: Registry login    
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: actions/checkout@master

      - uses: .github/actions/build

      - uses: .github/actions/build
        with:
          images: false
          chapters: true