name: images-linux-amd64

on:
  push:
    branches:
      - "2e"
    paths:
      - ".github/workflows/images-linux-amd64.yaml"
  workflow_dispatch:
    inputs:
      filter:
        required: false
        default: ''
        description: "Image filter"

jobs:
  images-linux-amd64:
    runs-on: ubuntu-ltest
    steps:
      - name: Registry login    
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: actions/checkout@master
      - uses: ./.github/actions/build
        with:
          filter: "${{ github.event.inputs.filter }}"