name: Windows LTSC2019 image build

on:
  push:
    branches:
      - "2e"
    paths:
      - "images/**"
      - "build/**"
      - ".github/workflows/images-windows-ltsc2019.yaml"

jobs:
  images-windows-ltsc2019:
    runs-on: windows-2019
    steps:

      - name: Docker Hub login
        working-directory: build
        shell: pwsh
        run: |
          docker login -u $env:USER -p $env:TOKEN
        env:
          USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: actions/checkout@master

      - name: Build Git Windows image
        uses: ./.github/actions/build
        with:
          filter: 'git-windows'

      - name: Build base images
        uses: ./.github/actions/build

      - name: Build chapter images
        uses: ./.github/actions/build
        with:
          images: 'false'
          chapters: 'true'
